LeapMask CWF
ScottKwang/CodeWithFriends-Spring2020 pull request #19
Opened 2020-05-24 13:24 UTC by Cipulot

# Hello there ;)

That's my pull request for the CWF project that I've been working on...

2020-05-29 19:17 UTC, hellomayuko requested changes
Wow this is so cool!!!!! This is definitely a project @ScottKwang would appreciate, since he used to do image recognition stuff too. It sounds like a really technical project, so congrats to you on finishing it!

Before we merge this, do you mind moving the `LeapMask.py` file into your `projects/Cipulot` subdirectory? Otherwise, this is all good to go!

2020-05-29 20:02 UTC, Cipulot commented
@hellomayuko all done ;)

2020-05-30 05:17 UTC, ScottKwang approved these changes
Yoooo. Loved the video you posted in Discord. Very surprised it worked as well as it did on the specs you used, great work.

Thanks for being a part of CWF, and congrats on your project!
Fill out this form by Monday to receive your sticker in the mail! https://forms.gle/zy6nr8czF4uoRA4j9

2020-05-30 05:18 UTC, merged

2020-05-30 10:26 UTC, Cipulot commented
@ScottKwang yeah, it was a bit challenging making it to work on my rig... I've just filled out the form that you indicated me.

Thanks again to you and Mayuko for this fantastic event, it really showed how even in these times people can join forces on creating innovative and fun projects in a collaborative environment.
Can't wait to join on the next CWF :)